apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: automation-workflow-dev

resources:
- namespace.yaml
- ../../base
- nats.configmap.yaml
- mongodb.configmap.yaml

patches:
- path: workflow.patch.deployment.yaml
- path: webhook-trigger.patch.deployment.yaml
- path: slack-worker.patch.deployment.yaml

images:
- name: workflow
  newName: ssrth/automation-workflow
  newTag: v1.0.0
