services:
  nats:
    container_name: nats
    image: nats:2.11.1
    ports:
      - 4222:4222
    command: --user root --pass root -js
    restart: always

  mongo:
    container_name: mongo
    image: mongo:8.0.9
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./.volumes/mongodb:/data/db

  # nats-setup:
  #   container_name: nats-setup
  #   depends_on:
  #     - nats
  #   image: bitnami/natscli:0.2.1
  #   volumes:
  #     - ./nats-setup.sh:/opt/app/nats-setup.sh
  #   entrypoint: [ "sh", "-c", "/opt/app/nats-setup.sh && exit 0"]

  example-basic-workflow:
    container_name: example-basic-workflow
    # depends_on:
    #   - nats-setup
    build:
      dockerfile: ./examples/basic/Dockerfile.base
      context: .
    volumes:
      - .:/opt/app
    working_dir: /opt/app
    command: /bin/sh -c 'go run examples/basic/cmd/workflow/main.go'
    restart: always
    environment: &common_env
      NATS_HOST: nats
      NATS_PORT: 4222
      NATS_USER: root
      NATS_PASSWORD: root
      NATS_STREAM_PREFIX: local
      NATS_CONSUMER_ID_PREFIX: local
      MONGODB_URI: mongodb://root:password@mongo:27017/
      MONGODB_DB_NAME: wf

  example-basic-worker-a:
    container_name: example-basic-worker-a
    depends_on:
      - example-basic-workflow
    build:
      dockerfile: ./examples/basic/Dockerfile.base
      context: .
    volumes:
      - .:/opt/app
    working_dir: /opt/app
    command: /bin/sh -c 'go run examples/basic/cmd/worker-a/main.go'
    restart: always
    environment: *common_env
    ports:
      - 8081:8080
  
  example-basic-worker-b:
    container_name: example-basic-worker-b
    depends_on:
      - example-basic-workflow
    build:
      dockerfile: ./examples/basic/Dockerfile.base
      context: .
    volumes:
      - .:/opt/app
    working_dir: /opt/app
    command: /bin/sh -c 'go run examples/basic/cmd/worker-b/main.go'
    restart: always
    environment: 
      NATS_HOST: nats
      NATS_PORT: 4222
      NATS_USER: root
      NATS_PASSWORD: root
      NATS_STREAM_PREFIX: local
      NATS_CONSUMER_ID_PREFIX: local
      MONGODB_URI: mongodb://root:password@mongo:27017/
      MONGODB_DB_NAME: wf
      SLACK_WEBHOOK_URL: ${SLACK_WEBHOOK_URL}
